### ISSUE TITLE
PDF viewer won't show up

### ISSUE THREAD

**Issue by andkamau** [CodeForAfrica/aleph#11]
https://data.investigativecenters.org/text/14158?page=1

Clues:

1. JS console: 
```Mixed Content: The page at 'https://data.investigativecenters.org/text/14158?page=1' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://data.investigativecenters.org/api/1/documents/14158/pdf'. This request has been blocked; the content must be served over HTTPS```
(Yet URL scheme is HTTPS)

2. Nginx redirects HTTP traffic to HTTPS

3. Aleph URL scheme is set to HTTPS

<img width="1314" alt="screen shot 2016-09-19 at 01 41 14" src="https://cloud.githubusercontent.com/assets/647123/18619641/4a776bb2-7e0a-11e6-9dd6-da7ed12a7d42.png">

**Comment by andkamau** [comment]
Full JS Console logs:

[js-console.txt](https://github.com/CodeForAfrica/aleph/files/479025/js-console.txt)

**Comment by andkamau** [comment]
Grateful if you could take a quick look, @pudo , @mevey , @DavidLemayian

**Comment by pudo** [comment]
Calling http://data.investigativecenters.org/api/1/documents/14158/pdf directly actually gives a different error, indicating something funky happened while importing the data. This might be a bug in the software, I'll investigate.

**Comment by andkamau** [comment]
The correct reference for this particular issue is:  https://data.investigativecenters.org/text/14158?page=1

**Comment by pudo** [comment]
Looks like the issue was that aleph got confused over the MIME type of the file, since it's extension is ``.1``, not ``.pdf``. I've added a fix to ``master`` on my repo which forces an appropriate mime type to be set. Hope that helps

**Comment by andkamau** [comment]
thanks @pudo for https://github.com/CodeForAfrica/aleph/commit/b070cd74d09f593d8ca3315cc97d156871dd7b88

any ideas on the PDF viewer issue https://github.com/CodeForAfrica/aleph/issues/11#issuecomment-247943014?

**Comment by andkamau** [comment]
Underlying error:

```
UnexpectedResponseException {name: "UnexpectedResponseException", message: "Unexpected server response (0) while retrieving PD…http://localhost:13376/api/1/documents/111/file".", status: 0}message: "Unexpected server response (0) while retrieving PDF "http://localhost:13376/api/1/documents/111/file"."name: "UnexpectedResponseException"stack: (...)status: 0__proto__: Error
    at UnexpectedResponseExceptionClosure (http://localhost:13376/static/vendor/pdfjs-dist/build/pdf.js:496:43)
    at http://localhost:13376/static/vendor/pdfjs-dist/build/pdf.js:500:3
    at PDFJS (http://localhost:13376/static/vendor/pdfjs-dist/build/pdf.js:61:5)
    at pdfjsWrapper (http://localhost:13376/static/vendor/pdfjs-dist/build/pdf.js:63:2)
    at http://localhost:13376/static/vendor/pdfjs-dist/build/pdf.js:9166:4
```

**Comment by andkamau** [comment]
Resolved by matching the same root volumes on web and worker container root variables.
